# Generated by Django 4.1.7 on 2023-02-22 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 22, 16, 33, 7, 410452)),
            preserve_default=False,
        ),
    ]
