# Generated by Django 4.1.7 on 2023-02-23 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universes', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universes.universe'),
        ),
    ]
